Areas/Admin/Controllers/POSController.cs
using Newtonsoft.Json.Linq;
using QLBH_MCDONALDS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLBH_MCDONALDS.Areas.Admin.Controllers
{
    public class POSController : Controller
    {
        private QLCuaHangMcDonaldEntities db = new QLCuaHangMcDonaldEntities();
        // GET: Admin/POS
        public ActionResult Index(string id, string MaSp)
        {

            List<SanPham> sp = db.SanPhams.Where(s => s.MaSP == MaSp).ToList();

            if (MaSp != null)
            {
                var sanPham = db.SanPhams
             .Where(s => s.MaSP == MaSp)
             .Select(s => new
             {
                 masp = s.MaSP,
                 TenSanPham = s.TenSP,
                 giatien = s.Gia
             })
             .FirstOrDefault(); // Lấy ra sản phẩm đầu tiên hoặc null nếu không tìm thấy

                if (Session["MyArray"] != null)
                {

                    // Ép kiểu Session["MyArray"] về kiểu mảng bạn đã lưu(ở đây là string[])
                    List<Donhang> retrieveobject = (List<Donhang>)Session["MyArray"];

                    bool contains = retrieveobject.Any(donhang => donhang.ma_san_pham == MaSp);

                    if (contains)
                    {
                        Donhang donhangToUpdate = retrieveobject.First(donhang => donhang.ma_san_pham == MaSp);
                        donhangToUpdate.soluong += 1;
                        Session["MyArray"] = retrieveobject;
                        ViewData["listOrdered"] = retrieveobject;
                    }
                    else
                    {
                        Donhang san_p = new Donhang
                        {
                            san_pham = sanPham.TenSanPham,
                            ma_san_pham = sanPham.masp,
                            gia = (int)sanPham.giatien,
                            soluong = 1,
                        };



                        retrieveobject.Add(san_p);
                        Session["MyArray"] = retrieveobject;
                    }
                }



                else
                {

                    List<Donhang> retrieveobject = new List<Donhang>();
                    Donhang san_p = new Donhang
                    {
                        san_pham = sanPham.TenSanPham,
                        ma_san_pham = sanPham.masp,
                        gia = (int)sanPham.giatien,
                        soluong = 1,
                    };
                    retrieveobject.Add(san_p);
                    Session["MyArray"] = retrieveobject;

                }
            }
            ViewData["listOrdered"] = Session["MyArray"];
            if (id == null || id == "All")
                return View(db.SanPhams.ToList());
            else
                return View(db.SanPhams.Where(s => s.MaLoai == id).ToList());


        }

        public ActionResult Delete_sp(string MaSp)
        {

            if (Session["MyArray"] != null)
            {

                // Ép kiểu Session["MyArray"] về kiểu mảng bạn đã lưu(ở đây là string[])
                List<Donhang> retrieveobject = (List<Donhang>)Session["MyArray"];


                Donhang donhangToRemove = retrieveobject.FirstOrDefault(donhang => donhang.ma_san_pham == MaSp);
                if (donhangToRemove != null)
                {
                    retrieveobject.Remove(donhangToRemove);
                    Session["MyArray"] = retrieveobject;

                }
                ViewData["listOrdered"] = retrieveobject;
            }


            return RedirectToAction("Index");


        }
        string LayMaHD()
        {
            var maMax = db.HoaDons.ToList().Select(n => n.MaHoaDon).Max();
            int maHD = int.Parse(maMax.Substring(2)) + 1;
            string HD = String.Concat("000", maHD.ToString());
            return HD.Substring(maHD.ToString().Length - 1);
        }
        /// //////////////////////////////////////////////////////////////////
        //THÊM ĐƠN HÀNG VÀO HÓA ĐƠN & CHI TIẾT HÓA ĐƠN
        [HttpPost]
        public ActionResult Index(string submit)
        {
            if (submit == "order" && Session["MyArray"] != null)
            {
                HoaDon hd = new HoaDon();
                hd.MaHoaDon = LayMaHD();
                hd.TrangThai = 0;
                hd.NgayLapHD = DateTime.Now;
                db.HoaDons.Add(hd);
                db.SaveChanges();
                foreach (var item in Session["MyArray"] as IEnumerable<Donhang>)
                {

                    ChiTietHoaDon ct = new ChiTietHoaDon();
                    ct.MaHoaDon = hd.MaHoaDon;
                    ct.MaSP = item.ma_san_pham;
                    ct.SoLuongSP = item.soluong;
                    db.ChiTietHoaDons.Add(ct);
                }
                db.SaveChanges();
                TempData["SuccessMessage"] = "Thanh toán thành công!";
                Session["MyArray"] = null;
                ViewData["listOrdered"] = null;
            }
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/POS/Index.cshtml
@model IEnumerable<QLBH_MCDONALDS.Models.SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-danger">ĐẶT HÀNG</strong>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-7">
                    <div>
                        <h4>Loại hàng</h4>
                        <div class="d-flex" style="overflow-x:scroll">
                            <a href="@Url.Action("Index", "POS", new { @id = "All"})" class="rounded-pill text-center border" style="min-width: 100px; margin: 5px; padding: 5px 10px; background: #d7d4bf3d; cursor:pointer">Tất cả</a>
                            @foreach (var item in new QLBH_MCDONALDS.Models.QLCuaHangMcDonaldEntities().LoaiSPs.ToList())
                            {
                                <a href="@Url.Action("Index", "POS", new { @id = item.MaLoai})" class="rounded-pill text-center border" style="min-width: 100px; margin: 5px; padding: 5px 10px; background: #d7d4bf3d; cursor:pointer">@item.TenLoai</a>
                            }
                        </div>
                    </div>
                    <div>
                        <h4>Danh sách sản phẩm</h4>
                        <div class="d-flex flex-row col-12 flex-wrap">
                            @foreach (var item in Model)
                            {
                               
                                <a href="@Url.Action("Index", "POS", new { @MaSp = @item.MaSP})" class="col-sm-2 rounded-pill text-center border"
                                   style="margin: 5px; padding: 5px 10px; background: #d7d4bf3d; cursor:pointer"
                                   onclick="them_sp('@item.MaSP')">
                                    <strong>@item.TenSP</strong>
                                    <div class="divider border-top"></div>
                                    @item.Gia VNĐ
                                </a>
                            }



                        </div>
                    </div>
                </div>
                <div class="col-md-5 p-2 rounded" style="background: grey;">
                    @Html.Partial("_PartialOrder", ViewData["listOrdered"])
                </div>
            </div>
        </div> <!-- /.card-footer-->
    </div><!-- /.card -->
</section><!-- /.content -->


<script>
    function them_sp(productId) {
        // Chuyển người dùng đến trang khác với ID của sản phẩm
        // Thay đổi đường dẫn (URL) dựa trên productId
        
        List < string > tempList = myArray.ToList(); // Chuyển mảng thành danh sách để dễ thao tác
        tempList.Add(productId); // Thêm phần tử vào danh sách
        myArray = tempList.ToArray(); // Chuyển danh sách thành mảng trở lại
        window.location.href = '/Product/Detail/' + productId;
    }
</script>

Areas/Admin/Views/POS/_PartialOrder.cshtml
@{
    int sum = 0;
}

<div class="col-md-12 ">
    <!--REVIEW ORDER-->
    <div class="panel panel-default">
        <div class="panel-heading text-center text-white">
            <h4>Đơn hàng</h4>
        </div>
        <div class="panel-body" style="background: white;">
            <table class="table border" style="height: 50vh; overflow-y: scroll;">
                <thead>
                    <tr>
                        <td class="text-center">Sản phẩm</td>
                        <td class="text-center">Giá tiền</td>
                        <td class="text-center">Số lượng</td>
                        <td class="text-right">Thành tiền</td>
                        <td class="text-right">   </td>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewData["listOrdered"] != null && ViewData["listOrdered"] is IEnumerable<QLBH_MCDONALDS.Models.Donhang>)
                    {
                        foreach (var item in ViewData["listOrdered"] as IEnumerable<QLBH_MCDONALDS.Models.Donhang>)
                        {
                            decimal itemTotal = item.soluong * item.gia; // Tính tổng tiền của sản phẩm hiện tại

                            <tr>
                                <td class="text-center">@item.san_pham</td>
                                <td class="text-center">@item.gia VNĐ</td>
                                <td class="text-center">@item.soluong</td>
                                <td class="text-right">@itemTotal VND</td>
                                <td>
                                    <a href="@Url.Action("Delete_sp", "POS", new { MaSp = item.ma_san_pham })" class="btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                                </td>

                            </tr>
                            sum += (int)itemTotal;
                        }
                    }

                </tbody>
            </table>
            
            <div class="col-md-12 text-right">
                @if (TempData["SuccessMessage"] != null)
                {
                    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
                }
                <strong>Tổng tiền</strong>
                <div class="pull-right"><span>@sum VND </span></div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input name="submit" value="order" hidden />
                <button type="submit" class="btn btn-primary rounded-0 btn-lg btn-block">Đặt hàng</button>
            }

        </div>

    </div>
    <!--REVIEW ORDER END-->
</div>